version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./webcontent:/usr/share/nginx/html
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"