name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-docker-app:latest .

      - name: Run tests
        run: docker run --rm my-docker-app:latest /run-tests.sh

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: docker tag my-docker-app:latest fa28/my-docker-app:latest

      - name: Push Docker image
        run: docker push fa28/my-docker-app:latest
